name: CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit
          pre-commit install
      - name: Run pre-commit
        run: pre-commit run -a

  unit-test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install library
        run: poetry install

      - name: Run tests
        run: |
          poetry run python -m pytest

# This workflow triggers on pull requests to the main branch. It sets up a Python environment, installs dependencies, and runs tests using pytest.

